### PR TITLE
perf: copy raw data from original apk when saving

### PR DESCRIPTION
**Pull request by Axelen123**
Avoids having to recompress and recalculate the crc-32.

I have used tools like `zipalign` and the `-t` option of the `unzip` utility to validate these changes.

### CODE REVIEW

**Comment by Axelen123** [comment]
> Very nice work ! I found one issue on `ZipEntrySource#byte[] readRawFileData()` which loads entire bytes to memory.
> 
>     * I tested with apk file having 750Mb asset file, it takes more than 5x to write apk

Thank you for spotting that!

I have an idea on how to fix that tomorrow, but could you send me the name of the app you used to test?

**Comment by Axelen123** [comment]
I could also create one myself

**Comment by Axelen123** [comment]
I have refactored `ZipAlign` to reduce code duplication. The static methods are untested, but they should still work. I will test them later today.

Also, Writing archives with lots of small files feels slower compared to before I implemented the fix for large files. I will have to look into this.

**Comment by REAndroid** [comment]
This commit looks perfect 👌 
Let me run few tests

**Comment by REAndroid** [comment]
@Axelen123 going to close it

**Comment by Axelen123** [comment]
Sounds good

**Pull request closed without merging**
